catalog:
  vite: 'https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@1856'
  vite-plus: 'https://pkg.pr.new/voidzero-dev/vite-plus@1856'
  vitest: '4.1.9'
minimumReleaseAge: 60
blockExoticSubdeps: false
minimumReleaseAgeExclude:
  - '@voidzero-dev/*'
  - vite-plus
  - '@vitest/*'
  - vite
  - vitest
  - '@oxc-project/*'
  - '@oxlint/*'
  - oxfmt
  - oxlint-tsgolint
  - '@oxlint/binding-android-arm-eabi'
  - '@oxlint/binding-android-arm64'
  - '@oxlint/binding-darwin-arm64'
  - '@oxlint/binding-darwin-x64'
  - '@oxlint/binding-freebsd-x64'
  - '@oxlint/binding-linux-arm-gnueabihf'
  - '@oxlint/binding-linux-arm-musleabihf'
  - '@oxlint/binding-linux-arm64-gnu'
  - '@oxlint/binding-linux-arm64-musl'
  - '@oxlint/binding-linux-ppc64-gnu'
  - '@oxlint/binding-linux-riscv64-gnu'
  - '@oxlint/binding-linux-riscv64-musl'
  - '@oxlint/binding-linux-s390x-gnu'
  - '@oxlint/binding-linux-x64-gnu'
  - '@oxlint/binding-linux-x64-musl'
  - '@oxlint/binding-openharmony-arm64'
  - '@oxlint/binding-win32-arm64-msvc'
  - '@oxlint/binding-win32-ia32-msvc'
  - '@oxlint/binding-win32-x64-msvc'
  - oxlint
overrides:
  vite: 'catalog:'
  vitest: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
verifyDepsBeforeRun: install
